<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>CreeperGame</AssemblyName>
    <RootNamespace>CreeperGame</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="6.1.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
