using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CreeperGame;

/// <summary>
/// A hand-authored pixel bitmap, built at runtime from character-art strings.
///
/// Rotating or smoothly scaling pixel art destroys it, so these sprites are only
/// ever drawn at whole-number scales on integer pixel positions. Animation comes
/// from swapping frames and shifting parts by whole pixels.
/// </summary>
public class PixelSprite : IDisposable
{
    public Texture2D Texture { get; }
    public int Width { get; }
    public int Height { get; }

    public PixelSprite(GraphicsDevice device, string[] rows, IReadOnlyDictionary<char, Color> palette)
    {
        Height = rows.Length;
        Width = rows.Max(r => r.Length);

        var pixels = new Color[Width * Height];

        for (int y = 0; y < Height; y++)
        {
            string row = rows[y];
            for (int x = 0; x < row.Length; x++)
            {
                char c = row[x];
                if (c == '.' || c == ' ') continue;   // transparent

                // An unknown character means a typo in the art data; make it loud.
                pixels[y * Width + x] = palette.TryGetValue(c, out Color colour)
                    ? colour
                    : new Color(255, 0, 255);
            }
        }

        Texture = new Texture2D(device, Width, Height);
        Texture.SetData(pixels);
    }

    /// <summary>Draws with the top-left at the given pixel, at a whole-number scale.</summary>
    public void Draw(SpriteBatch spriteBatch, int screenX, int screenY, int scale,
        bool flip, Color tint)
    {
        spriteBatch.Draw(Texture,
            new Rectangle(screenX, screenY, Width * scale, Height * scale),
            null, tint, 0f, Vector2.Zero,
            flip ? SpriteEffects.FlipHorizontally : SpriteEffects.None, 0f);
    }

    public void Dispose() => Texture?.Dispose();
}

/// <summary>
/// Pixel artwork for the winged knight, transcribed from the concept art: closed
/// helm with a red plume, plated torso with a red sash, a long blade held upright,
/// a trailing cape and a feathered wing.
///
/// Authored facing right and mirrored when the knight turns. Generated by
/// design/art.py, which renders a preview so the art can be checked by eye.
/// </summary>
public static class KnightArt
{
    /// <summary>Height of the assembled knight in art pixels, heel to helm.</summary>
    public const int Height = 64;

    public static readonly Dictionary<char, Color> Palette = new()
    {
        ['k'] = new Color(10, 10, 14),
        ['D'] = new Color(38, 42, 54),
        ['d'] = new Color(62, 68, 84),
        ['s'] = new Color(96, 104, 124),
        ['l'] = new Color(140, 149, 170),
        ['w'] = new Color(186, 194, 212),
        ['W'] = new Color(232, 238, 248),
        ['r'] = new Color(52, 10, 16),
        ['R'] = new Color(92, 18, 26),
        ['B'] = new Color(134, 26, 34),
        ['C'] = new Color(172, 40, 46),
        ['b'] = new Color(20, 18, 24),
        ['n'] = new Color(32, 30, 38),
        ['F'] = new Color(240, 243, 250),
        ['f'] = new Color(202, 209, 224),
        ['g'] = new Color(152, 161, 182),
        ['G'] = new Color(104, 113, 136),
    };

    /// <summary>12 x 14 pixels.</summary>
    public static readonly string[] Head =
    {
        "...kkkkkk...",
        "..kDDDDDDk..",
        ".kDdddddddk.",
        ".kDdsssssdk.",
        "kDdsslllssdk",
        "kDdslllllsdk",
        "kDdkkkkkksdk",
        "kDdslllllsdk",
        "kDdsslllssdk",
        ".kDdsssssdk.",
        ".kDddsssddk.",
        "..kDdddddk..",
        "...kkDDkk...",
        "....knnk....",
    };

    /// <summary>10 x 10 pixels.</summary>
    public static readonly string[] Plume =
    {
        ".......kCk",
        "......kCBk",
        ".....kCBRk",
        "....kCBRrk",
        "...kCBRrk.",
        "..kCBRrk..",
        ".kBRrrk...",
        "kBRrk.....",
        "kRrk......",
        "kkk.......",
    };

    /// <summary>16 x 20 pixels.</summary>
    public static readonly string[] Torso =
    {
        "..kkkkkkkkkkkk..",
        ".kDDddddddddDDk.",
        "kDddsssslllssddk",
        "kDdsssslllllssdk",
        "kDdssslllwwlllsk",
        "kDdsslllwWWwllsk",
        "kDdsslllwWWwllsk",
        "kDdssslllwwlllsk",
        "kDdsssslllllssdk",
        "kDddsssslllsssdk",
        ".kDdssssslllssdk",
        ".kDdssssssslssdk",
        ".kDddsssssssssdk",
        "..kDdsssssssssk.",
        "..kCCBBBBBBBCCk.",
        "..kBRRrrrrrrRBk.",
        "..kBRRrrrrrrRBk.",
        "...kDddssssddk..",
        "...kDdsslllsdk..",
        "....kDddddddk...",
    };

    /// <summary>7 x 15 pixels.</summary>
    public static readonly string[] ArmNear =
    {
        ".kkkkk.",
        "kDdsslk",
        "kDdsslk",
        "kDdsslk",
        "kDdsslk",
        ".kdsslk",
        ".kdsslk",
        ".kdsslk",
        ".kdsslk",
        ".kdsslk",
        ".kdsslk",
        ".kwwwlk",
        ".kwWwlk",
        ".kwwwlk",
        "..kkkk.",
    };

    /// <summary>6 x 15 pixels.</summary>
    public static readonly string[] ArmFar =
    {
        ".kkkk.",
        "kDdddk",
        "kDddsk",
        "kDddsk",
        "kDddsk",
        "kDddsk",
        "kDddsk",
        "kDddsk",
        "kDddsk",
        "kDddsk",
        "kDddsk",
        "kDdssk",
        "kDdssk",
        "kDdssk",
        ".kkkk.",
    };

    /// <summary>7 x 35 pixels.</summary>
    public static readonly string[] Sword =
    {
        "...k...",
        "..kWk..",
        "..kWk..",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        ".kdWlk.",
        "kkkkkkk",
        "kdBCBdk",
        "kkkkkkk",
        "..knk..",
        "..knk..",
        "..knk..",
        "..knk..",
        ".kdwdk.",
        ".kkkkk.",
    };

    /// <summary>20 x 16 pixels.</summary>
    public static readonly string[] LegsIdle =
    {
        "..kDddk...kdddk.....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "...kDdsk...kddsk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "...kDssk...kddsk....",
        "..kbbbbk..kbbbbk....",
        ".kbbbbbbkkbbbbbbk...",
        ".kkkkkkkkkkkkkkkk...",
    };

    /// <summary>21 x 16 pixels.</summary>
    public static readonly string[] LegsWalk0 =
    {
        "....kDddk.kdddk......",
        "...kDsslk..kdsslk....",
        "..kDsslk....kdsslk...",
        ".kDsslk......kdsslk..",
        ".kDsslk.......kdssk..",
        "kDdsk..........kddsk.",
        "kDsslk.........kdsslk",
        "kDsslk.........kdsslk",
        "kDssk..........kdsslk",
        "kbbbk...........kbbbk",
        "kbbbbk.........kbbbbk",
        "kkkkkk.........kkkkkk",
        ".....................",
        ".....................",
        ".....................",
        ".....................",
    };

    /// <summary>20 x 16 pixels.</summary>
    public static readonly string[] LegsWalk1 =
    {
        "..kDddk...kdddk.....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        ".kDsslk....kdsslk...",
        ".kDsslk....kdsslk...",
        "kDdsk.......kddsk...",
        "kDsslk......kdsslk..",
        "kDsslk......kdsslk..",
        "kDsslk......kdsslk..",
        "kDssk.......kdssk...",
        "kbbbbk.....kbbbbk...",
        "kbbbbbk...kbbbbbbk..",
        "kkkkkkk...kkkkkkkk..",
        "....................",
        "....................",
        "....................",
    };

    /// <summary>20 x 16 pixels.</summary>
    public static readonly string[] LegsWalk2 =
    {
        "..kDddk...kdddk.....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "...kDdsk...kddsk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "..kDsslk..kdsslk....",
        "...kDssk...kddsk....",
        "..kbbbbk..kbbbbk....",
        ".kbbbbbbkkbbbbbbk...",
        ".kkkkkkkkkkkkkkkk...",
    };

    /// <summary>21 x 16 pixels.</summary>
    public static readonly string[] LegsWalk3 =
    {
        "...kDddk..kdddk......",
        "....kDsslk.kdsslk....",
        ".....kDsslk.kdsslk...",
        "......kDsslk.kdssk...",
        ".......kDssk..kddsk..",
        "........kDdsk..kdssk.",
        ".......kDsslk..kdsslk",
        "......kDsslk...kdsslk",
        "......kDssk....kbbbk.",
        ".....kbbbbk...kbbbbk.",
        "....kbbbbbbk..kkkkkk.",
        "....kkkkkkkk.........",
        ".....................",
        ".....................",
        ".....................",
        ".....................",
    };

    /// <summary>20 x 16 pixels.</summary>
    public static readonly string[] LegsCrouch =
    {
        "....................",
        "....................",
        "....................",
        "....................",
        "..kDddk...kdddk.....",
        ".kDsslsk.kdsslsk....",
        ".kDsslsk.kdsslsk....",
        "kDdsslk.kddsslk.....",
        "kDsslk..kdsslk......",
        "kDssk...kdssk.......",
        "kbbbk...kbbbk.......",
        "kbbbbbkkbbbbbk......",
        "kkkkkkkkkkkkkk......",
        "....................",
        "....................",
        "....................",
    };

    /// <summary>21 x 16 pixels.</summary>
    public static readonly string[] LegsJump =
    {
        "....kDddk.kdddk......",
        "...kDsslk..kdsslk....",
        "...kDsslk...kdsslk...",
        "..kDdsk......kdssk...",
        "..kDsslk......kddsk..",
        ".kDsslk........kdsslk",
        ".kDssk.........kdsslk",
        "kbbbbk..........kbbbk",
        "kbbbbbk........kbbbbk",
        "kkkkkkk........kkkkkk",
        ".....................",
        ".....................",
        ".....................",
        ".....................",
        ".....................",
        ".....................",
    };

    /// <summary>20 x 16 pixels.</summary>
    public static readonly string[] LegsFall =
    {
        "..kDddk...kdddk.....",
        "..kDsslk..kdsslk....",
        ".kDsslk....kdsslk...",
        ".kDsslk....kdsslk...",
        "kDdsk.......kddsk...",
        "kDsslk......kdsslk..",
        "kDsslk.......kdsslk.",
        "kDsslk.......kdsslk.",
        "kDssk.........kdssk.",
        "kbbbbk.......kbbbbk.",
        "kbbbbbk.....kbbbbbbk",
        "kkkkkkk.....kkkkkkkk",
        "....................",
        "....................",
        "....................",
        "....................",
    };

    /// <summary>20 x 16 pixels.</summary>
    public static readonly string[] LegsDash =
    {
        "....................",
        "....................",
        "....................",
        "..........kDdddk....",
        ".........kDsssslk...",
        "........kDsssslk....",
        "kkk....kDdssslk.....",
        "kbbk..kDsssslk......",
        "kbbbkkDssslk........",
        ".kbbbDsslk..........",
        "..kbbbbbbk..........",
        "..kkkkkkkk..........",
        "....................",
        "....................",
        "....................",
        "....................",
    };

    /// <summary>15 x 23 pixels.</summary>
    public static readonly string[] CapeRest =
    {
        "...kkkkkkkk....",
        "..kCBBBBBBCk...",
        "..kBRRRRRRBk...",
        ".kBRRrrrrRRBk..",
        ".kBRrrrrrrrRk..",
        ".kBRrrRRrrrRk..",
        "kBRrrrRRrrrRk..",
        "kBRrrrRRrrrRk..",
        "kRRrrrRRrrrRk..",
        "kRrrrrRRrrrRk..",
        "kRrrrrRRrrrRk..",
        "kRrrrrRRrrRk...",
        "kRrrrrRRrrRk...",
        ".kRrrrRRrrRk...",
        ".kRrrrRRrrRk...",
        ".kRrrrRRrRk....",
        "..kRrrRRrRk....",
        "..kRrrRRrRk....",
        "...kRrrRrRk....",
        "...kRrrrrk.....",
        "....kRrrrk.....",
        "....kkrrkk.....",
        ".....kkkk......",
    };

    /// <summary>15 x 23 pixels.</summary>
    public static readonly string[] CapeDrift =
    {
        "....kkkkkkkk...",
        "...kCBBBBBBCk..",
        "..kBRRRRRRRBk..",
        "..kBRRrrrrRRk..",
        ".kBRRrrrrrrRk..",
        ".kBRrrRRrrrRk..",
        "kBRrrrRRrrrRk..",
        "kBRrrRRrrrrRk..",
        "kRRrrRRrrrrRk..",
        "kRrrRRrrrrRk...",
        "kRrrRRrrrRk....",
        "kRrRRrrrrRk....",
        "kRRRrrrrRk.....",
        "kRRrrrrRk......",
        "kRrrrrRk.......",
        "kRrrrRk........",
        "kRrrRk.........",
        "kRrRk..........",
        "kRrk...........",
        "kkk............",
        "...............",
        "...............",
        "...............",
    };

    /// <summary>15 x 23 pixels.</summary>
    public static readonly string[] CapeStream =
    {
        "........kkkkkkk",
        "......kkCBBBBBk",
        "...kkkCBBRRRRRk",
        "kkkCBBRRRrrrrRk",
        "kCBBRRrrrrrrrRk",
        "kBRRrrrrrrrrRk.",
        "kBRrrrrrrrrRk..",
        "kRRrrrrrrrRk...",
        "kRrrrrrrRk.....",
        "kRrrrrRk.......",
        "kRrrRk.........",
        "kkrk...........",
        "...............",
        "...............",
        "...............",
        "...............",
        "...............",
        "...............",
        "...............",
        "...............",
        "...............",
        "...............",
        "...............",
    };

    /// <summary>16 x 24 pixels.</summary>
    public static readonly string[] WingFolded =
    {
        "....kkkk........",
        "...kFFFfk.......",
        "..kFFFfgk.......",
        "..kFFfggk.......",
        ".kFFfgGkk.......",
        ".kFFfgGk........",
        ".kFfgGkk........",
        "kFFfgGk.........",
        "kFfgGkk.........",
        "kFfgGk..........",
        "kfgGkk..........",
        "kfgGk...........",
        "kgGkk...........",
        "kgGk............",
        "kGkk............",
        "kGk.............",
        "kk..............",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    };

    /// <summary>16 x 24 pixels.</summary>
    public static readonly string[] WingOpen =
    {
        "........kkkkkk..",
        "......kkFFFFFfk.",
        "....kkFFFFFffgk.",
        "..kkFFFFFffggGk.",
        "kkFFFFFffgkkkk..",
        "kFFFFffggk......",
        "kFFFffgkk.......",
        "kFFffgk.........",
        "kFFfgkk.........",
        "kFffgk..........",
        "kFfgkk..........",
        "kFfgk...........",
        "kfgkk...........",
        "kfgk............",
        "kgkk............",
        "kgk.............",
        "kk..............",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    };

    /// <summary>16 x 24 pixels.</summary>
    public static readonly string[] WingSpread =
    {
        "....kkkkkkkkkk..",
        "..kkFFFFFFFFFfk.",
        "kkFFFFFFFFFFffk.",
        "kFFFFFFFFFFfffk.",
        "kFFFFFFFFFffggk.",
        "kFFFFFFFFffggGk.",
        "kFFFFFFFffggkk..",
        "kFFFFFFffggk....",
        "kFFFFFffggk.....",
        "kFFFFffggk......",
        "kFFFffggk.......",
        "kFFffggk........",
        "kFfffgk.........",
        "kFffgk..........",
        "kFfgk...........",
        "kffgk...........",
        "kfgk............",
        "kgk.............",
        "kk..............",
        "................",
        "................",
        "................",
        "................",
        "................",
    };

}